name: Writing
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true

# Permalinks
permalink: /:categories/:title/

exclude: [
          README.md
         ]

include: [
          .htaccess
         ]