name: Writing
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis",
               "fenced_code_blocks",
               "autolink",
               "tables",
               "with_toc_data",
               "strikethrough"]
pygments: true

# excerpt_separator: "\n\n\n"

# Permalinks
permalink: /:categories/:title/

# Server
#source:           src
#destination:      _gh_pages
#host:             0.0.0.0
#url:              localhost
#port:             9001
#baseurl:          /
#encoding:         UTF-8


paginate_path: 'blog/page/:num'
paginate:      5


exclude: ["README.md"]

include: [".htaccess"]
